# Usa una imagen base de OpenJDK
FROM openjdk:17-jdk-slim
# Añade un argumento para la versión de Spring Boot
ARG JAR_FILE=transactionms/target/*.jar

# Copia el archivo JAR generado en el contenedor
COPY ${JAR_FILE} app.jar

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 8180

# Define el comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "/app.jar"]