server:
  port: 8180
  undertow:
    worker-threads: 20
spring:
  database:
    user: desarrollo
    pass: desa123
    jdbcUrl: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    dbName: postgres
    hostPort: localhost:5432
    connTimeout: 10000
    maxPoolSize: 20
    minimunIdle: 1
    idleTimeout: 10000
    maxLifeTime: 60000
    leakDetectionThreshold: 0
    max-wait: 7000
    max-active: 10
    max-idle: 5
    min-idle: 1
    initial-size: 10
    test-on-borrow: true
    test-while-idle: true
    validation-query: "SELECT 1"
    validation-interval: 30000
    connection-properties: SERVER_INITIATED_TRANSACTIONS=false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ms-transaction-mq
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
security:
  basic: 
     enabled: false
  ignored: /**
